AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Java SAM backend with Cognito User Pool and protected HttpApi

Globals:
  Function:
    Runtime: java17
    MemorySize: 512
    Timeout: 15
    Tracing: Active

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${AWS::StackName}-userpool
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireUppercase: true
          RequireNumbers: true
          RequireSymbols: false

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: !Sub ${AWS::StackName}-appclient
      GenerateSecret: false
      PreventUserExistenceErrors: ENABLED
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default
      CorsConfiguration:
        AllowOrigins: ['*']
        AllowHeaders: ['*']
        AllowMethods: ['GET', 'POST', 'OPTIONS']
      Auth:
        Authorizers:
          CognitoAuthorizer:
            IdentitySource: "$request.header.Authorization"
            JwtConfiguration:
              issuer: !GetAtt UserPool.ProviderURL
              audience:
                - !Ref UserPoolClient

  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello
      Handler: com.example.hello.HelloHandler::handleRequest
      Description: Protected hello endpoint that echoes JWT info
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        HelloRoute:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /hello
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer

Outputs:
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
  UserPoolClientId:
    Description: Cognito User Pool App Client ID
    Value: !Ref UserPoolClient
  HttpApiEndpoint:
    Description: Base URL of the HTTP API
    Value: !GetAtt HttpApi.ApiEndpoint

